CREATE DATABASE BDBiblioteca;
DROP DATABASE BDBiblioteca;

-- TABLAS SIN DEPENDENCIA
use BDBiblioteca;
CREATE TABLE TPais (
	nPaisID NUMERIC(3,0) NOT NULL UNIQUE PRIMARY KEY,
    cNombre VARCHAR(30) NOT NULL
);

use BDBiblioteca;
CREATE TABLE TSocio (
cNIF CHAR(9) PRIMARY KEY,
    cNombre VARCHAR(30) NOT NULL,
    cApellidos VARCHAR(60) NOT NULL,
    cDireccion VARCHAR(100),
    cTelefono CHAR(12) NOT NULL,
    dNacimiento DATE NOT NULL,
    dAlta DATE NOT NULL CHECK (dAlta >= '2003-09-01')
);

use BDBiblioteca;
CREATE TABLE TTema (
    nTemaID INT PRIMARY KEY AUTO_INCREMENT,
    cNombre VARCHAR(50) NOT NULL UNIQUE
);

use BDBiblioteca;
CREATE TABLE TAutor (
    nAutorID INT PRIMARY KEY AUTO_INCREMENT,
    cNombre VARCHAR(30) NOT NULL,
    cApellidos VARCHAR(60) NOT NULL
);

-- TABLAS CON DEPENDENCIAS SIMPLES
use BDBiblioteca;
CREATE TABLE TEditorial (
	nEditorialID INT PRIMARY KEY AUTO_INCREMENT,
	cNombre VARCHAR(40) NOT NULL UNIQUE,
	nPaisID NUMERIC(3,0) DEFAULT 724, 
	FOREIGN KEY (nPaisID) REFERENCES TPais (nPaisID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION
);

use BDBiblioteca;
CREATE TABLE TLibro (
    nLibroID INT PRIMARY KEY AUTO_INCREMENT,
    cTitulo VARCHAR(200) NOT NULL UNIQUE,
    nAnyoPublicacion NUMERIC(4,0) NOT NULL, 
    nEditorialID INT NOT NULL,
	FOREIGN KEY (nEditorialID) REFERENCES TEditorial (nEditorialID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- TABLAS CON DEPENDENCIAS COMPUESTAS
use BDBiblioteca;
CREATE TABLE TEjemplar (
    cSignatura VARCHAR(15) PRIMARY KEY, 
    nLibroID INT NOT NULL,
	FOREIGN KEY (nLibroID) REFERENCES TLibro (nLibroID)
        ON UPDATE CASCADE
        ON DELETE CASCADE 
);

use BDBiblioteca;
CREATE TABLE TPrestamo (
	cSignatura VARCHAR(15) NOT NULL,
	cNIF CHAR(9) NOT NULL,
	dPrestamo DATE NOT NULL,
	PRIMARY KEY (cSignatura, cNIF, dPrestamo),
	FOREIGN KEY (cSignatura) REFERENCES TEjemplar (cSignatura)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (cNIF) REFERENCES TSocio (cNIF)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- TABLAS DE RELACIÓN N:M
use BDBiblioteca;
CREATE TABLE TLibroTema (
    nLibroID INT NOT NULL,
    nTemaID INT NOT NULL,
    PRIMARY KEY (nLibroID, nTemaID),
    FOREIGN KEY (nLibroID) REFERENCES TLibro (nLibroID)
        ON UPDATE CASCADE
        ON DELETE CASCADE, 
    FOREIGN KEY (nTemaID) REFERENCES TTema (nTemaID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

use BDBiblioteca;
CREATE TABLE TLibroAutor (
    nLibroID INT NOT NULL,
    nAutorID INT NOT NULL,
    PRIMARY KEY (nLibroID, nAutorID),
    FOREIGN KEY (nLibroID) REFERENCES TLibro (nLibroID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (nAutorID) REFERENCES TAutor (nAutorID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

use BDBiblioteca;
CREATE TABLE TAutorPais (
    nAutorID INT NOT NULL,
    nPaisID NUMERIC(3,0) NOT NULL,
    PRIMARY KEY (nAutorID, nPaisID),
    FOREIGN KEY (nAutorID) REFERENCES TAutor (nAutorID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (nPaisID) REFERENCES TPais (nPaisID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);